openapi: 3.0.0
info:
  title: Social App
  description: our first Social app at Lco - Gaurav
  version: 1.0.1
servers:
  - url: http://localhost:4000/api/v1
    description: localhost version of our app
  - url: http://localhost:4000/api/v1
    description: it's a dummy api ,It doesn't work

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary: returns username , followers and follows
      responses:
      '200': #status code
      description: returns an object
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
              followers:
                type: string
              follows:
                type: string
